stages:
  - build

build:8:
  image: haskell:8
  stage: build
  script:
    - cabal update
    - cabal install --installdir public --install-method copy
    - zip -r public/hsc3-graphs.zip public/hsc3-graphs
  rules:
    - when: manual
  artifacts:
    paths:
      - public/hsc3-graphs.zip
