echo adc; grep \(adc\) */*.hs | wc -l
echo am; grep \(am\) */*.hs | wc -l
echo f0; grep \(f0\) */*.hs | wc -l
echo jl; grep \(jl\) */*.hs | wc -l
echo jmcc; grep \(jmcc\) */*.hs | wc -l
echo jrhb; grep \(jrhb\) */*.hs | wc -l
echo nc; grep \(nc\) */*.hs | wc -l
echo nv; grep \(nv\) */*.hs | wc -l
echo rd; grep \(rd\) */*.hs | wc -l
