clone-oscjs:
	git clone https://github.com/colinbdclark/osc.js/

fetch-oscjs:
	(cd osc.js ; git pull)

clone-jssc3:
	git clone https://gitlab.com/rd--/jssc3

fetch-jssc3:
	(cd jssc3 ; git pull)

clone-scsynth:
	git clone https://gitlab.com/rd--/scsynth-wasm-builds

fetch-scsynth:
	(cd scsynth-wasm-builds ; git pull)
