; pluck
(let* ((n 25)
       (gen (lambda (n f) (mce-fill n (lambda (_) (f)))))
       (f (gen n (lambda () (Rand 0.05 0.2))))
       (p (gen n (lambda () (Rand 0 1))))
       (x (MouseX kr 60 1000 1 0.1))
       (o (lin-lin (SinOsc kr f p) -1 1 x 3000))
       (w (clone n (lambda () (Mul (WhiteNoise ar) 0.1))))
       (i (Impulse kr (gen n (lambda () (Rand 10 12))) 0))
       (ks (Pluck w i 0.01 (FDiv 1 o) 2 (Rand 0.01 0.2)))
       (l (gen n (lambda () (Rand -1 1)))))
  (LeakDC (mix (Pan2 ks l 1)) 0.995))
