; red frik (f0)
(let* ((red
        (lambda (tr n)
          (let* ((r1 (TRand 0.3 3 tr))
                 (r2 (TRand 0.3 5 tr))
                 (r3 (TRand 0 0.5 tr))
                 (r4 (TRand 0.49 0.56 tr))
                 (r5 (TRand 0.3 0.6 tr))
                 (r6 (TRand 0.3 0.5 tr))
                 (o1 (MulAdd (FSinOsc kr r2 0) r3 r4))
                 (o2 (Mul (FSinOsc kr o1 r5) r6)))
            (RHPF n r1 o2))))
       (n (clone 2 (lambda () (BrownNoise ar))))
       (tr (Impulse kr 0.1 0)))
  (Mul (red tr n) 0.1))
