; diffraction (rd)
(let* ((mk-p
         (lambda ()
           (let* ((x (MouseX kr 0.001 0.02 1 0.1))
                  (y (MouseY kr 120 400 1 0.1))
                  (f (Mul (LFNoise0 kr 4) (mce2 32 64)))
                  (w (Mul (LFNoise0 kr 32) x)))
             (Mul (Resonz (Pulse ar f w)
                          (Add y (Mul (LFNoise0 kr 2) 0.1))
                          (MulAdd (LFNoise0 kr 6) 0.4 0.8))
                  0.5))))
       (q (CombN (mk-p)
                  0.2
                  (MulAdd (LFNoise0 kr 128) 0.1 0.1)
                  3))
       (r (let* ((x (MouseX kr 0.75 1.25 1 0.1))
                 (y (MouseY kr 0.25 1 1 0.1))
                 (f (lambda (_)
                      (Mul (SinOsc ar (Mul x (Rand 50 59)) 0)
                           (Mul y (Rand 0.04 0.16))))))
            (mce2 (mix-fill 16 f)
                  (mix-fill 12 f)))))
  (Sum3 (mk-p) q r))
