; synthetic piano (jmcc) #3
(!+
 (lambda ()
    (let* ((n (IRand 36 90))
           (f (Rand 0.1 0.5))
           (ph (Rand 0 1))
           (s (Mul (Impulse f ph) 0.1))
           (e (Decay2 s 0.008 0.04))
           (c (lambda (o)
                (let* ((n0 (LfNoise2 3000))
                       (dt (Div 1 (MidiCps (Add n o)))))
                  (CombL (Mul n0 e) dt dt 6))))
           (l (Sub (Div (Sub n 36) 27) 1)))
      (Pan2 (Mix (map c (list -0.05 0 0.05))) l 1)))
  6)
