; trkl (rd)
(let ((trkl
       (lambda (d ul fu dy la fy)
         (let* ((tf (XLine kr 1 ul d removeSynth))
                (st (Impulse ar (Mul tf 8) 0))
                (t  (Impulse ar tf 0))
                (a  (DbAmp (Line kr 12 la d removeSynth)))
                (f  (XLine kr fu 900 d removeSynth))
                (p  (Line kr (Rand -1 1) (Rand -1 1) d removeSynth))
                (fh (TRand 1.75 2.25 t)))
           (Pan2 (Add (Mix (Ringz (Decay2 t 0.01 dy) (Mce2 f (Mul f fh)) fy))
                      (Mix (Mul3 (Saw ar (Mce2 f (Mul f fh)))
                                 (Decay2 t 0.1 (TRand 0.05 1.0 t))
                                 (TExpRand 0.001 0.25 st))))
                 p a)))))
  (trkl (Rand 0.5 16)
        (Rand 16 64)
        (Rand 1200 9000)
        (Rand 0.005 0.175)
        (Rand -60 -25)
        (Rand 0.015 0.125)))
