; metal plate (jmcc)
(let* ((sr 48000)
       (n 4)
       (maxdt (ceiling (* sr 0.03)))
       (buf (map (lambda (_) (ClearBuf (LocalBuf 1 maxdt))) (enum-from-to 1 n)))
       (tap-tm (_replicate-m n (Rand 0.015 0.03)))
       (exc-freq (MouseY kr 10 8000 linear 0.2))
       (exc-trig (Mul (Impulse ar 0.5 0) 0.2))
       (exc (Mul (Decay2 exc-trig 0.01 0.2) (LFNoise2 ar exc-freq)))
       (del (zip-with (lambda (b tm) (tap 1 ar b tm)) buf tap-tm))
       (flt-freq (MouseX kr 10 5000 linear 0.2))
       (flt (map (lambda (i) (Mul (LPF i flt-freq) 0.98)) del))
       (rb (lambda (b f) (RecordBuf ar b 0 1 0 1 loop 1 do-nothing (Add f exc))))
       (wr (zip-with rb buf flt)))
  (mrg-n (cons (foldr1 Add flt) wr)))
