; ccomb (rd)
(let* ((rng (lambda (u l r) (lin-lin u -1 1 l r)))
       (lwr 48)
       (flwr (MIDICPS 48))
       (spart (lambda (t)
                (let* ((n (rng (LFNoise2 kr 0.1) lwr 72))
                       (e (Decay2 t 0.01 (TRand 0.05 0.75 t)))
                       (x (Mul (WhiteNoise ar) e))
                       (m (LFNoise2 kr 0.1))
                       (f (Lag (MIDICPS n) 0.25)))
                  (CombC x (Recip flwr) (Recip f) (rng m 1.0 8.0)))))
       (t (Dust ar (mce2 0.9 0.8))))
  (mix-fill 7 (lambda (_) (Mul (spart t) 0.05))))
