; trmlo (rd)
(let*
    ((m-wrp
      (lambda (i l r)
        (lin-lin i -1 1 (MIDICPS l) (MIDICPS r))))
     (m-wrp1
      (lambda (i m)
        (m-wrp i m (Add m 1))))
     (m-wrp-n
      (lambda (i m n)
        (m-wrp i m (Add m n))))
     (o1
      (let* ((f 5)
             (d 3)
             (s (env-sine d 0.1))
             (e (EnvGen kr 1 1 0 1 do-nothing s))
             (n 65)
             (m (SinOsc kr f 0)))
        (Pan2 (SinOsc ar (m-wrp1 m n) 0) m e)))
     (o2
      (let* ((f (IRand 5 9))
             (d (IRand 5 9))
             (s (env-sine d (Rand 0.1 0.2)))
             (e (EnvGen kr 1 1 0 1 do-nothing s))
             (n (IRand 69 72))
             (m (SinOsc kr f 0)))
        (Pan2 (SinOsc ar (m-wrp1 m n) 0) m e)))
     (o3
      (let* ((f (IRand 5 9))
             (d (IRand 9 12))
             (s (env-sine d (Rand 0.1 0.2)))
             (e (EnvGen kr 1 1 0 1 do-nothing s))
             (n (IRand 69 72))
             (m (SinOsc kr f 0))
             (l (Line kr 0 (IRand 1 5) d do-nothing)))
        (Pan2 (Blip ar (m-wrp1 m (Add n l)) (lin-lin m -1 1 1 2)) m e)))
     (o4
      (let* ((f (IRand 5 18))
             (d (IRand 12 15))
             (s (env-sine d (Rand 0.1 0.2)))
             (e (EnvGen kr 1 0.05 0 1 do-nothing s))
             (n (IRand 69 72))
             (m (SinOsc kr f 0))
             (l (Line kr 0 (IRand 1 5) d remove-synth))
             (fr (m-wrp-n m (Add n l) (IRand 1 5))))
        (Pan2 (Blip ar fr (lin-lin m -1 1 1 (IRand 2 24))) m e))))
  (Sum4 o1 o2 o3 o4))
