; fm-iter (rd)
(let* ((t0 (Impulse ar (Recip 0.30) 0))
       (t1 (TDelay t0 0.15))
       (t (Mce2 t0 t1))
       (k (TRand 56 57 t))
       (i (TRand 40 480 t))
       (j (TRand -1 1 t))
       (c (MIDICPS k))
       (m (MIDICPS (Sum3 k 1 j)))
       (s (envPerc 0.01 0.9 1 (list -4 -4)))
       (e (EnvGen ar t 0.1 0 1 removeSynth s))
       (f (MulAdd (SinOsc ar c 0) i m)))
  (Mul (SinOsc ar f 0) e))
