; aleatoric quartet (jmcc) #7
(let* ((amp 0.4)
       (density (MouseX kr 0.01 1 0 0.1))
       (dmul (Mul (Recip density) (Mul 0.5 amp)))
       (dadd (Add (Neg dmul) amp))
       (rapf (lambda (i)
               (let ((r (mce2 (Rand 0 0.05) (Rand 0 0.05))))
                 (AllpassN i 0.05 r 1))))
       (rapfn (lambda (n i)
                ((foldl1 compose (replicate n rapf)) i)))
       (mk-f (lambda ()
               (let* ((i0 (IRand 0 2))
                      (r0 (Select i0 (mce3 1 0.5 0.25)))
                      (r1 (Rand -30 30))
                      (n0 (LFNoise0 kr r0))
                      (m (Round (MulAdd n0 7 (Add 66 r1)) 1)))
                 (MIDICPS (Lag m 0.2)))))
       (mk-s (lambda (_)
               (let* ((f (Recip (mk-f)))
                      (r (Rand -1 1))
                      (n0 (PinkNoise ar))
                      (n1 (LFNoise1 kr 8))
                      (x (Mul n0 (Max 0 (MulAdd n1 dmul dadd)))))
                 (Pan2 (CombL x 0.02 f 3) r 1))))
       (g (mix-fill 4 mk-s)))
  (Mul (LeakDC (rapfn 4 g) 0.995) 0.25))
