; lucier (cr) ; http://illposed.com/
(let* ((freq (ctl "freq" 60))
       (crr (Recip (ControlRate)))
       (mkDt (lambda (f) (Sub (Recip f) crr)))
       (stringDelay (mkDt freq))
       (pk1Pos 0.1)
       (srcPos 0.3)
       (pk2Pos 0.9)
       (maxDelay 1.0)
       (mkDelay (lambda (i r) (LPZ1 (DelayC i maxDelay (Mul r stringDelay)))))
       (mkAllpass (lambda (i r dt) (LPZ1 (AllpassC i maxDelay (Mul r stringDelay) dt))))
       (drv (LocalIn 1 0))
       (pk1R (let ((i drv) (r (Sub srcPos pk1Pos))) (mkDelay i r)))
       (pk1L (let ((i (Mul pk1R (negate 1)))
                    (r (Mul pk1Pos 2))
                    (dt (Rand 0.001 0.11)))
                (mkAllpass i r dt)))
       (pk2L (let ((i pk1L) (r (Sub pk2Pos pk1Pos))) (Mul (mkDelay i r) 0.99)))
       (stringL (let ((i pk2L) (r (Sub 1.0 pk2Pos))) (mkDelay i r)))
       (pk2R (let ((i (Mul stringL (negate 1)))
                    (r (Sub 1.0 pk2Pos))
                    (dt (Add 2 (Rand 0.001 0.11))))
                (Mul (mkAllpass i r dt) 0.99)))
       (stringR (let ((i pk2R) (r (Sub pk2Pos srcPos))) (mkDelay i r)))
       (source (let* ((s (Mul (SinOsc 220 0) 0.01))
                      (p (Mul (Pulse (Add 60 (Mul (Amplitude drv 0.01 0.01) 11)) 0.5) 0.1))
                      (f (RLPF (Add s p) 320 0.05)) (e (Sub 1.0 (Min (Amplitude drv 0.01 0.01) 1.0))))
                 (Mul (Normalizer f 0.7 0.01) e)))
       (lOut (LocalOut (Add (Mul source 0.2) stringR)))
       (outL (Add pk1L pk1R)) (outR (Add pk2L pk2R)))
  (Mrg (list (Mce2 outL outR) drv source lOut)))
