; 20060914 (rd) ; texture=overlap,21,0,3,inf ; requires=kr:
(let* ((chrd
        (lambda (m)
          (let* ((ds 3)
                 (d (map (lambda (x) (* x ds)) (list 5 4 5 7 4 5)))
                 (f (MidiCps (XLn m (Add m (Rand 0.05 0.5)) d)))
                 (z (EnvTrapezoid 0 (Rand 0.15 0.35) d (Rand 0.005 0.01)))
                 (e (EnvGen 1 1 0 1 doNothing z))
                 (p (XLn (Rand -1 1) (Rand -1 1) d))
                 (o (FSinOsc f 0)))
            (Mix (Pan2 o p e)))))
       (scale (list 0 2 4 5 7 9 11))
       (octaves (list 4 5 6 7))
       (mnn (concat (map (lambda (n) (map (lambda (o) (+ n (* o 12))) octaves)) scale)))
       (chd (replicateM 6 (lambda () (kr: (Select (IRand 0 (length mnn)) mnn))))))
  (!+ (lambda () (chrd chd)) 5))
