; deep sea (jrhb)
(let* ((range (lambda (s l r) (let ((m (Mul (Sub r l) 0.5))) (MulAdd s m (Add m l)))))
       (amp 1)
       (pan 0)
       (variation 0.9)
       (n (Rand 7 46))
       (dt1 (Add 25 (Rand -1.7 1.7)))
       (dt2 (Mul3 (Add dt1 (LFNoise2 kr 2)) variation 0.001))
       (frEQ (Add 901 (Rand 0 65)))
       (t (Mul (Impulse ar (Recip dt2) 0) 100))
       (count (PulseCount t 0))
       (ml (LT count n))
       (u1 (Mul (BPF (Mul ml t) frEQ 1) 0.1))
       (freq2 (Mul frEQ (Add (Mod count (range (LFNoise1 kr 1) 2 20)) 1)))
       (u2 (Mul (BPF u1 freq2 1) 0.2)))
  (Mrg2 (Pan2 u2 pan (Mul amp 10))
        (DetectSilence u2 0.0001 0.2 removeSynth)))
