; doppler (jmcc)
(let* ((doppler
        (lambda (xy s)
          (let* ((d (Hypot (car xy) (cdr xy)))
                 (a (Fdiv 40 (Squared d)))
                 (maxd 110))
            (Mul (DelayL s (Fdiv maxd 344) (Fdiv d 344)) a))))
       (line-x (lambda (x y dt) (cons x (Line (Neg y) y dt doNothing))))
       (ellipse
        (lambda (a b dt)
          (let ((t (Line (Neg twoPi) (Mul pi 1.5) dt removeSynth)))
            (cons (Mul a (Cos t)) (Mul b (Sin t))))))
       (src (RLPF (Mul (FSinOsc 200 0) (LFPulse 31.3 0 0.4)) 400 0.3)))
  (Mce2 (doppler (line-x 10 100 6) src)
        (doppler (ellipse 10 75 12) src)))
