; doppler (jmcc)
(let* ((doppler
        (lambda (xy s)
          (let* ((d (Hypot (car xy) (cdr xy)))
                 (a (FDiv 40 (Squared d)))
                 (maxd 110))
            (Mul (DelayL s (FDiv maxd 344) (FDiv d 344)) a))))
       (line-x (lambda (x y dt) (cons x (Line kr (Neg y) y dt do-nothing))))
       (ellipse
        (lambda (a b dt)
          (let ((t (Line kr (Neg two-pi) (Mul pi 1.5) dt remove-synth)))
            (cons (Mul a (Cos t)) (Mul b (Sin t))))))
       (src (RLPF (Mul (FSinOsc ar 200 0) (LFPulse ar 31.3 0 0.4)) 400 0.3)))
  (mce2 (doppler (line-x 10 100 6) src)
        (doppler (ellipse 10 75 12) src)))
