; tr-out (rd)
(let* ((mk-read (lambda (l t) (buf-rd-n 1 kr (as-local-buf l) (t-rand 0 6 t) 0)))
       (mk-node
        (lambda (n)
          (let* ((t (dust kr 1.6))
                 (f (midi-cps (mk-read (list 60 62 64 65 67 69) t)))
                 (p (mk-read (list -1 -0.5 0 0.25 0.75 1.0) t))
                 (a (mk-read (list 0.01 0.05 0.1 0.15 0.25 0.35) t)))
            (cons (pan2 (sin-osc ar f 0) p a)
                  (send-trig t n (f-div f 660))))))
       (ns (map mk-node (enum-from-to 1 4))))
  (mrg-n (cons (mul (foldl1 add (map car ns)) 0.25)
               (map cdr ns))))
