; aleatoric quartet (jmcc) #7 ; requires=kr:
(let* ((amp 0.4)
       (density (MouseX 0.01 1 0 0.1))
       (dmul (Mul (Recip density) (Mul 0.5 amp)))
       (dadd (Add (Neg dmul) amp))
       (rapf (lambda (i)
               (let ((r (Mce2 (Rand 0 0.05) (Rand 0 0.05))))
                 (AllpassN i 0.05 r 1))))
       (mk-f (lambda ()
               (let* ((i0 (IRand 0 2))
                      (r0 (kr: (Select i0 (Mce3 1 0.5 0.25))))
                      (r1 (Rand -30 30))
                      (n0 (LfNoise0 r0))
                      (m (RoundTo (MulAdd n0 7 (Add 66 r1)) 1)))
                 (MidiCps (Lag m 0.2)))))
       (mk-s (lambda ()
               (let* ((f (Recip (mk-f)))
                      (r (Rand -1 1))
                      (n0 (PinkNoise))
                      (n1 (LfNoise1 8))
                      (x (Mul n0 (Max 0 (MulAdd n1 dmul dadd)))))
                 (Pan2 (CombL x 0.02 f 3) r 1))))
       (g (!+ mk-s 4)))
  (Mul (LeakDc (iter 4 rapf g) 0.995) 0.25))
