; pv_magabove
(let* ((b (ctl kr "buf" 0))
       (a (PlayBuf 1 ar b (BufRateScale kr b) 0 0 loop do-nothing))
       (x (MouseX kr 1 100 0 0.1))
       (y (MouseY kr 0 1 0 0.1))
       (c1 (fft* (LocalBuf 1 2048) a))
       (c2 (PV_Copy c1 (LocalBuf 1 2048)))
       (c3 (PV_MagBelow c1 x))
       (c4 (PV_MagAbove c2 x)))
  (Mul (mce2 (ifft* c3) (ifft* c4)) (mce2 y (Sub 1 y))))
