; sidereal time (jmcc) #9 ; texture=overlap,4,4,6,inf
(let* ((p 15)
       (z (let ((mk-y (lambda ()
                        (let ((fr (RExpRandN p 100 6000))
                              (rt (RRandN p 2 6)))
                          (klank-data-mce fr (make-mce (replicate p 1)) rt)))))
            (clone 2 mk-y)))
       (f (XLine kr (ExpRand 40 300) (ExpRand 40 300) 12 do-nothing))
       (t (let ((e (LFNoise2 kr (Rand 0 8))))
            (Mul (Mul (LFPulse ar f 0 (Rand 0.1 0.9)) 0.002) (Max 0 e))))
       (o (Mul (Distort (Klank t 1 0 1 (mce-transpose z))) 0.1)))
  (Add (CombN o 0.6 (Rand 0.1 0.6) 8) (mce-reverse o)))
