; strummable guitar (jmcc) #11
(let* ((scale (list 52 57 62 67 71 76))
       (str (lambda (i)
              (let* ((x (MouseX 0 1 0 0.2))
                     (t (Abs (HPZ1 (Gt x (Add 0.25 (Mul i 0.1))))))
                     (e (Decay t 0.05))
                     (n (Mul (PinkNoise) e))
                     (dt (Recip (MidiCps (list-ref scale i))))
                     (s (CombL n dt dt 4)))
                (Pan2 s (Sub (Mul i 0.2) 0.5) 1))))
       (strs (mixFill (length scale) str)))
  (LeakDC (LPF strs 12000) 0.995))
