; http://fredrikolofsson.com/f0blog/?q=node/478 (f0)
(let* ((a (lambda (n) (LFPulse ar n 0 0.5)))
       (b (mceFromTo 1 4))
       (a1 (FDiv (Add (a (FDiv b 32)) 1) 8))
       (a2 (Mul (Add (a a1) 1) b))
       (a3 (a (FDiv b 64)))
       (a4 (MulAdd (a (a (FDiv b 8))) 2 b))
       (a5 (a (FDiv 4 b))) (a6 (a a2))
       (a7 (a (Mul (Add a6 (Mul (Add (mix a3) a5) a4)) 100)))
       (s (FDiv (mix a7) 8)))
  (Mul (mce2 s s) 0.1))
