; pv_magabove
(let* ((b (ctl "buf" 0))
       (a (PlayBuf 1 b (BufRateScale b) 0 0 loop doNothing))
       (x (MouseX 1 100 0 0.1))
       (y (MouseY 0 1 0 0.1))
       (c1 (FftDefaults (LocalBuf 1 2048) a))
       (c2 (PV_Copy c1 (LocalBuf 1 2048)))
       (c3 (PV_MagBelow c1 x))
       (c4 (PV_MagAbove c2 x)))
  (Mul (Mce2 (IfftDefaults c3) (IfftDefaults c4)) (Mce2 y (Sub 1 y))))
