; tipnso (rd)
(let* ((t (Impulse ar (MouseX kr 1 32 0 0.1) 0))
       (e (Decay2 t 0.01 (Mce2 0.1 0.15)))
       (n (TIRand 16 72 t))
       (f (MIDICPS (Add n (Add 36 (Mul 12 (TIRand 0 1 t)))))))
  (Mrg2 (Mul (Add (Mul (SinOsc ar f 0) e)
                  (BPF (Mul (PinkNoise ar) e)
                       (Add 36 (MIDICPS n))
                       (FDiv 175 (MIDICPS n))))
             (Mce2 0.15 0.1))
        (SendTrig t 0 n)))
