; plucked strings (jmcc)
(let ((s (lambda (_)
           (let* ((s0 (Mul (Impulse (Rand 2 2.2) 0) 0.3))
                  (s1 (Mul (Dust 0.5) 0.3))
                  (f (MulAdd (SinOsc (Rand 0.05 0.15) (Rand 0 (* pi 2))) 5 5.2))
                  (s2 (Mul (Impulse f 0) 0.3))
                  (im (kr (Select (IRand 0 2) (Mce3 s0 s1 s2))))
                  (dt (Fdiv 1 (MidiCps (Floor (Rand 60 90)))))
                  (t (Mul3 (Decay im 0.1) (PinkNoise) 0.1)))
             (Pan2 (CombL t dt dt 4) (Rand -1 1) 1)))))
  (LeakDC (mixFill 5 s) 0.96))
