; red frik (f0)
(let* ((red
        (lambda (tr n)
          (let* ((r1 (TRand 0.3 3 tr))
                 (r2 (TRand 0.3 5 tr))
                 (r3 (TRand 0 0.5 tr))
                 (r4 (TRand 0.49 0.56 tr))
                 (r5 (TRand 0.3 0.6 tr))
                 (r6 (TRand 0.3 0.5 tr))
                 (o1 (MulAdd (SinOsc r2 0) r3 r4))
                 (o2 (Mul (SinOsc o1 r5) r6)))
            (Rhpf n r1 o2))))
       (n (Dup (lambda () (BrownNoise)) 2))
       (tr (Impulse 0.1 0)))
  (Mul (red tr n) 0.1))
