; doppler (jmcc)
(let* ((doppler
        (lambda (xy s)
          (let* ((d (hypot (car xy) (cdr xy)))
                 (a (f-div 40 (squared d)))
                 (maxd 110))
            (mul (delay-l s (f-div maxd 344) (f-div d 344)) a))))
       (line-x (lambda (x y dt) (cons x (line kr (neg y) y dt do-nothing))))
       (ellipse
        (lambda (a b dt)
          (let ((t (line kr (neg two-pi) (mul pi 1.5) dt remove-synth)))
            (cons (mul a (u:cos t)) (mul b (u:sin t))))))
       (src (rlpf (mul (f-sin-osc ar 200 0) (lf-pulse ar 31.3 0 0.4)) 400 0.3)))
  (mce2 (doppler (line-x 10 100 6) src)
        (doppler (ellipse 10 75 12) src)))
